package zej.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import zej.bean.Classes;
import zej.bean.ClassesExample;
import zej.bean.GradeExample;

public interface ClassesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_classes
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    long countByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_classes
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int deleteByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_classes
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int deleteByPrimaryKey(String classesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_classes
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int insert(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_classes
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int insertSelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_classes
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    List<Classes> selectByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_classes
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    Classes selectByPrimaryKey(String classesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_classes
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Classes record, @Param("example") ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_classes
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int updateByExample(@Param("record") Classes record, @Param("example") ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_classes
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int updateByPrimaryKeySelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_classes
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int updateByPrimaryKey(Classes record);
    
    List<Classes> selectByGradeExample(GradeExample example);//根据年级查找年级中所有的班级
}