package zej.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import zej.bean.Classes;
import zej.bean.Grade;
import zej.bean.GradeExample;

public interface GradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_grade
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    long countByExample(GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_grade
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int deleteByExample(GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_grade
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int deleteByPrimaryKey(Integer gradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_grade
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_grade
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int insertSelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_grade
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    List<Grade> selectByExample(GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_grade
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Grade record, @Param("example") GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_grade
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int updateByExample(@Param("record") Grade record, @Param("example") GradeExample example);
    
   
    
}