package zej.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import zej.bean.ClassesExample;
import zej.bean.Student;
import zej.bean.StudentExample;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_student
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    long countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_student
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_student
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_student
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_student
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_student
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_student
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    Student selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_student
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_student
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_student
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_student
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    int updateByPrimaryKey(Student record);
    List<Student> selectByExampleWithClasses(ClassesExample example);
    Student selectByPrimaryKeyWithClasses(Integer studentId);
    Student lazySelectByPrimaryKey(Integer studentId);
    List<Student> selectByExampleWithAll(StudentExample example);
    Student selectByPrimaryKeyWithAll(Integer studentId);
}