package zej.bean;


public class Classes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_classes.classes_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    private String classesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_classes.classes_name
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    private String classesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_classes.grade_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    private Integer gradeId;

    private Grade grade;
    public Grade getGrade() {
		return grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_classes.classes_id
     *
     * @return the value of tbl_classes.classes_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public String getClassesId() {
        return classesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_classes.classes_id
     *
     * @param classesId the value for tbl_classes.classes_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public void setClassesId(String classesId) {
        this.classesId = classesId == null ? null : classesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_classes.classes_name
     *
     * @return the value of tbl_classes.classes_name
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public String getClassesName() {
        return classesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_classes.classes_name
     *
     * @param classesName the value for tbl_classes.classes_name
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public void setClassesName(String classesName) {
        this.classesName = classesName == null ? null : classesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_classes.grade_id
     *
     * @return the value of tbl_classes.grade_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_classes.grade_id
     *
     * @param gradeId the value for tbl_classes.grade_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }
    
 
}