package zej.bean;

import java.util.List;

public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_grade.grade_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    private Integer gradeId;

    

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_grade.grade_id
     *
     * @return the value of tbl_grade.grade_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_grade.grade_id
     *
     * @param gradeId the value for tbl_grade.grade_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }
}