package zej.bean;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_student.student_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_student.student_name
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_student.student_sex
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    private String studentSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_student.student_age
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    private Integer studentAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_student.classes_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    private String classesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_student.student_id
     *
     * @return the value of tbl_student.student_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    private Classes classes;
   

	public Classes getClasses() {
		return classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_student.student_id
     *
     * @param studentId the value for tbl_student.student_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_student.student_name
     *
     * @return the value of tbl_student.student_name
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_student.student_name
     *
     * @param studentName the value for tbl_student.student_name
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_student.student_sex
     *
     * @return the value of tbl_student.student_sex
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public String getStudentSex() {
        return studentSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_student.student_sex
     *
     * @param studentSex the value for tbl_student.student_sex
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public void setStudentSex(String studentSex) {
        this.studentSex = studentSex == null ? null : studentSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_student.student_age
     *
     * @return the value of tbl_student.student_age
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public Integer getStudentAge() {
        return studentAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_student.student_age
     *
     * @param studentAge the value for tbl_student.student_age
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public void setStudentAge(Integer studentAge) {
        this.studentAge = studentAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_student.classes_id
     *
     * @return the value of tbl_student.classes_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public String getClassesId() {
        return classesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_student.classes_id
     *
     * @param classesId the value for tbl_student.classes_id
     *
     * @mbg.generated Sun Apr 01 16:39:14 CST 2018
     */
    public void setClassesId(String classesId) {
        this.classesId = classesId == null ? null : classesId.trim();
    }
}